
FROM node:alpine

RUN apk update
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates \
    tzdata \
    git \
    nginx \
    gettext
    
RUN mkdir /Sub-Store \
    && mkdir /Sub-Store/nginx

ENV FRONT_END="https://github.com/sunchaowang/sub-store-frontend.git"
ENV BACK_END="https://github.com/sunchaowang/sub-store-backend.git"
ENV DOKCER="https://github.com/sunchaowang/sub-store-docker.git"
ENV DOMIAN="/"
ENV TZ=Asia/Shanghai

WORKDIR /Sub-Store
RUN cd /Sub-Store \
    && git clone ${FRONT_END} Front \
    && git clone ${BACK_END} Back \
    && git clone ${DOKCER} Docker

RUN mkdir -p /etc/nginx/conf.d \
    && cp -r /Sub-Store/Docker/nginx/front* /etc/nginx/conf.d/ \
    && cp -r /Sub-Store/Docker/nginx/nginx.conf /etc/nginx/

RUN npm i pnpm pm2 -g

RUN chmod 777 /Sub-Store/Docker/docker/sub-store.sh

ENTRYPOINT ["/bin/sh","/Sub-Store/Docker/docker/sub-store.sh" ]